"""
Pydantic Schemas for API Requests, Responses, and Agent Data Models.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SeverityEnum(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class Finding(BaseModel):
    """Represents an individual issue or finding discovered by an agent."""
    id: Optional[str] = Field(default=None, description="Unique finding ID, e.g. SEC-001")
    severity: SeverityEnum = Field(description="Severity classification")
    category: str = Field(description="Finding category, e.g. injection, complexity, docstring")
    title: str = Field(description="Short, human-readable summary of the issue")
    message: str = Field(description="Detailed explanation of what was found")
    line: Optional[int] = Field(default=None, description="Line number in source code")
    column: Optional[int] = Field(default=None, description="Column offset in source code")
    code_snippet: Optional[str] = Field(default=None, description="Offending line or code block")
    explanation: Optional[str] = Field(default=None, description="Why this finding matters")
    recommendation: Optional[str] = Field(default=None, description="How to resolve the finding")
    suggestion: Optional[str] = Field(default=None, description="Concrete proposed code diff or replacement")
    cwe_id: Optional[str] = Field(default=None, description="Common Weakness Enumeration ID if applicable")
    cvss_score: Optional[float] = Field(default=None, description="CVSS 3.1 score between 0.0 and 10.0")
    exploitability: Optional[float] = Field(default=None, description="Estimated exploitability probability")
    false_positive_probability: Optional[float] = Field(default=0.02, description="Calculated FP probability")


class AgentResult(BaseModel):
    """Output generated by a single specialized review agent."""
    name: str = Field(description="Agent identifier: security, performance, quality, etc.")
    status: str = Field(default="completed", description="Status: completed, failed, or skipped")
    score: float = Field(default=100.0, ge=0.0, le=100.0, description="Agent-specific quality score")
    execution_time_ms: int = Field(default=0, description="Time taken to execute in milliseconds")
    findings: List[Finding] = Field(default_factory=list, description="Findings reported by this agent")
    error: Optional[str] = Field(default=None, description="Error message if agent execution failed")


class SeveritySummary(BaseModel):
    """Aggregated count of findings by severity level."""
    critical: int = 0
    high: int = 0
    medium: int = 0
    low: int = 0
    info: int = 0


class ReviewContext(BaseModel):
    """Contextual metadata about the source code being reviewed."""
    project_name: Optional[str] = None
    git_commit: Optional[str] = None
    file_path: Optional[str] = None
    git_branch: Optional[str] = None
    repo_owner: Optional[str] = None
    repo_name: Optional[str] = None


class ReviewConfig(BaseModel):
    """Review-specific configuration overrides."""
    severity_threshold: Optional[str] = "medium"
    blocking_mode: Optional[bool] = False
    custom_rules: Optional[List[str]] = None


class CodeReviewRequest(BaseModel):
    """Payload to submit code for multi-agent review."""
    code: str = Field(..., max_length=500000, description="Source code text to review")
    language: Optional[str] = Field(default="python", description="Programming language (e.g. python, javascript, sql)")
    filename: Optional[str] = Field(default="snippet.py", description="Source filename for context")
    context: Optional[ReviewContext] = Field(default_factory=ReviewContext)
    agents: Optional[List[str]] = Field(default=None, description="Specific agents to run. Defaults to all active.")
    config: Optional[ReviewConfig] = Field(default_factory=ReviewConfig)
    webhook_url: Optional[str] = Field(default=None, description="Optional webhook URL to receive results")
    webhook_secret: Optional[str] = Field(default=None, description="Secret token for HMAC webhook verification")
    async_mode: Optional[bool] = Field(default=False, description="Whether to queue review asynchronously")


class CodeReviewResponse(BaseModel):
    """Standard response containing review status and prioritized multi-agent findings."""
    review_id: str = Field(description="Unique review identifier, e.g. rev_8f7e6d5c4b3a2918")
    status: str = Field(description="processing, completed, failed")
    created_at: str
    completed_at: Optional[str] = None
    cache_hit: bool = False
    blocking: bool = False
    should_block: bool = False
    block_reason: Optional[str] = None
    overall_score: Optional[float] = None
    processing_time_ms: Optional[int] = None
    results: Optional[Dict[str, Any]] = None
    critical_issues: List[Finding] = Field(default_factory=list)
    warnings: List[Finding] = Field(default_factory=list)
    suggestions: List[Finding] = Field(default_factory=list)
    agents_scheduled: List[str] = Field(default_factory=list)
    webhook_url: Optional[str] = None
    _links: Optional[Dict[str, str]] = None


class BatchReviewRequest(BaseModel):
    """Batch review submission for multiple files or snippets."""
    files: List[CodeReviewRequest]
    project_name: Optional[str] = None


class BatchReviewResponse(BaseModel):
    batch_id: str
    total_files: int
    reviews: List[CodeReviewResponse]


class FeedbackRequest(BaseModel):
    rating: int = Field(ge=1, le=5, description="Star rating from 1 to 5")
    is_helpful: bool = True
    false_positives: int = 0
    false_negatives: int = 0
    comments: Optional[str] = None


class FeedbackResponse(BaseModel):
    status: str = "success"
    message: str = "Feedback recorded successfully"


class AgentInfo(BaseModel):
    id: str
    name: str
    version: str
    purpose: str
    capabilities: List[str]
    status: str = "active"


class HealthResponse(BaseModel):
    status: str
    version: str
    timestamp: str
    database: str
    cache: str
    active_agents: List[str]
    uptime_seconds: float
